apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy-configmap
  namespace: default
data:
  config.production.json: |
    {
        "ipaddress": "0.0.0.0",
        "port": 80,

        "routes": [
            {
                "route": "/total",
                "destination": "http://totalmarks"
            },
            {
                "route": "/next",
                "destination": "http://marksfornext"
            },
            {
                "route": "/sort",
                "destination": "http://sortmodules"
            },
            {
                "route": "/max",
                "destination": "http://maxmin"
            },
            {
                "route": "/classify",
                "destination": "http://classifygrade"
            },
            {
                "route": "/mean",
                "destination": "https://meanmark-service-development.azurewebsites.net/api/mean"
            },
            {
                "route": "/session",
                "destination": "https://stateful-saving-service-development.azurewebsites.net/api" 
            },
            {
                "route": "/monitoring",
                "destination": "http://monitoring" 
            },
            {
                "route": "/dogs",
                "destination": "https://dog.ceo/api/breeds/image/random"
            },
        ]
    }
