apiVersion: apps/v1
kind: Deployment
metadata:
  name: maxmin-deployment
  labels:
    tier: backend
spec:
  selector:
    matchLabels:
      app: v1
      service: maxmin
  replicas: 2
  template:
    metadata:
      name: maxmin
      labels:
        app: v1
        service: maxmin
    spec:
      containers:
        - name: maxmin
          image: registry.hal.davecutting.uk/40265748/assignment2-registry/maxmin:latest
          ports:
            - name: maxmin
              containerPort: 80
          env:
          - name: PORT
            value: "80"