apiVersion: apps/v1
kind: Deployment
metadata:
  name: total-deployment
  labels:
    tier: backend
spec:
  selector:
    matchLabels:
      app: v1
      service: totalmarks
  replicas: 2
  template:
    metadata:
      name: totalmarks
      labels:
        app: v1
        service: totalmarks
    spec:
      containers:
        - name: totalmarks
          image: registry.hal.davecutting.uk/40265748/assignment2-registry/totalmarks:latest
          ports:
            - name: total
              containerPort: 80
