# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Marks For Next Grade Service

on:
  push:
    branches: [ "master" ]
    paths:
      - "qubgrademe-marksfornext/**"
  pull_request:
    branches: [ "master" ]
    paths:
      - "qubgrademe-marksfornext/**"
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: qubgrademe-marksfornext/
        
    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: "Installing Packages"
      run: npm ci
    - name: "Running Tests"
      run: npm run test
