# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy dotnet core app to Azure Function App - stateful-saving-service

on:
  push:
    branches:
      - master
    paths:
      - "qubgrademe-statefulsaving/**"
  pull_request:
    branches:
      - master
    paths:
      - "qubgrademe-statefulsaving/**"
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: "./qubgrademe-statefulsaving/src" # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: "6.0.302" # set this to the dotnet version to use

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 'Resolve Project Dependencies Using Dotnet'
        shell: pwsh
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet build --configuration Release --output ./output
          popd

      - name: "Install Test Dependencies"
        shell: bash
        working-directory: qubgrademe-statefulsaving/tests
        run: dotnet restore

      - name: "Run Tests"
        shell: bash
        working-directory: qubgrademe-statefulsaving/tests
        run: dotnet test

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'stateful-saving-service'
          slot-name: 'development'
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_A8D6F853D6BF489D8B27CC2B844492A6 }}
