# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy dotnet core project to Azure Function App - MeanMarkService

on:
  push:
    branches:
      - master
    paths:
      - "qubgrademe-meanmark/**"
  pull_request:
    branches:
      - master
    paths:
      - "qubgrademe-meanmark/**"
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: "./qubgrademe-meanmark/src" # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '6.0.302' # set this to the dotnet version to use

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 'Resolve Project Dependencies Using Dotnet'
        shell: bash
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet build --configuration Release --output ./output
          popd

      - name: "Install Test Dependencies"
        shell: bash
        working-directory: qubgrademe-meanmark/test
        run: dotnet restore

      - name: "Run Tests"
        shell: bash
        working-directory: qubgrademe-meanmark/test
        run: dotnet test

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'meanmark-service'
          slot-name: 'Production'
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_5DDC5F040A954F5995246E9DE1DC6E26 }}
