name: Monitoring Service

on:
  push:
    branches: [ "master" ]
    paths:
      - "qubgrademe-monitoring/**"
  pull_request:
    branches: [ "master" ]
    paths:
      - "qubgrademe-monitoring/**"
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: qubgrademe-monitoring/

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal