name: TotalMarks Service

on:
  push:
    branches: [ "master" ]
    paths:
      - "qubgrademe-totalmarks/**"
  pull_request:
    branches: [ "master" ]
    paths:
      - "qubgrademe-totalmarks/**"
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: qubgrademe-totalmarks/

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./... -o main

    - name: Test
      run: go test -v ./...
